
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alexandre
 */
public class app extends javax.swing.JFrame {

    static int idFormando = 1;
    static int idCurso = 1;
    static int idDisciplina = 1;
    static ArrayList<Formando> osFormandos = new ArrayList<>();
    static ArrayList<Cursos> osCursos = new ArrayList<>();
    static ArrayList<Disciplinas> asDisciplinas = new ArrayList<>();
    static ArrayList<CursoDisci> osCursoDisci = new ArrayList<>();
    static ArrayList<Nomeado> nomed = new ArrayList<>();
    static ArrayList<CursoForm> osCursoForm = new ArrayList<>();

    /**
     * Creates new form app
     */
    public app() {

        initComponents();
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        jTabbedPane1.setEnabledAt(3, false);
        jTabbedPane1.setEnabledAt(4, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cursos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        horascurso = new javax.swing.JTextField();
        criarcurso = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rescur = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        discitext = new javax.swing.JTextField();
        createDisciplinas = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addDisciplinas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Resdis = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Resdis1 = new javax.swing.JTextArea();
        idCursodis = new javax.swing.JTextField();
        idDisciplinadis = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        inscreverBT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tele = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idcursoform = new javax.swing.JTextField();
        idformandoform = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        resformcur = new javax.swing.JTextArea();
        AddFormtoCur = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resgeral = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        idcursolistar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        apagarcurso = new javax.swing.JButton();
        apagardisci = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        apagaraluno = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        idcursolistar1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        idcursolistar2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        disciapagar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        apagacurse = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel11.setText("Bem-Vindo");

        Iniciar.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio", jPanel4);

        jLabel5.setText("Nome do Curso:");

        cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursosActionPerformed(evt);
            }
        });

        jLabel6.setText("Horas de Curso:");

        criarcurso.setText("Criar Curso");
        criarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarcursoActionPerformed(evt);
            }
        });

        rescur.setEditable(false);
        rescur.setColumns(20);
        rescur.setRows(5);
        jScrollPane2.setViewportView(rescur);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(horascurso, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cursos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(criarcurso)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horascurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(criarcurso)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Curso", jPanel2);

        jLabel7.setText("Nome da Disciplina:");

        createDisciplinas.setText("Criar Disciplina");
        createDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDisciplinasActionPerformed(evt);
            }
        });

        jLabel9.setText("ID Curso:");

        jLabel10.setText("Disciplina:");

        addDisciplinas.setText("Adicionar Disciplina");
        addDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDisciplinasActionPerformed(evt);
            }
        });

        Resdis.setEditable(false);
        Resdis.setColumns(20);
        Resdis.setRows(5);
        jScrollPane3.setViewportView(Resdis);

        Resdis1.setEditable(false);
        Resdis1.setColumns(20);
        Resdis1.setRows(5);
        jScrollPane5.setViewportView(Resdis1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idCursodis, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(idDisciplinadis))
                        .addGap(287, 287, 287)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(discitext, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createDisciplinas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addDisciplinas, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(discitext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(createDisciplinas)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(idCursodis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(idDisciplinadis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addDisciplinas)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Disciplina", jPanel3);

        jLabel1.setText("Nome:");

        inscreverBT.setText("Inscrever");
        inscreverBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscreverBTActionPerformed(evt);
            }
        });

        jLabel2.setText("Sexo:");

        jLabel3.setText("Telefone:");

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });

        res.setEditable(false);
        res.setColumns(20);
        res.setRows(5);
        jScrollPane1.setViewportView(res);

        jLabel4.setText("Id Curso:");

        jLabel8.setText("Id Formando: ");

        resformcur.setColumns(20);
        resformcur.setRows(5);
        jScrollPane6.setViewportView(resformcur);

        AddFormtoCur.setText("Adicionar");
        AddFormtoCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFormtoCurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddFormtoCur, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscreverBT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tele, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                        .addComponent(nome))
                                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idformandoform, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(idcursoform))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inscreverBT)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idcursoform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(idformandoform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddFormtoCur)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inscrição", jPanel1);

        resgeral.setEditable(false);
        resgeral.setColumns(20);
        resgeral.setRows(5);
        jScrollPane4.setViewportView(resgeral);

        jButton1.setText("Curso + Disciplina");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Curso + Aluno");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        apagarcurso.setText("Apagar Curso");
        apagarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarcursoActionPerformed(evt);
            }
        });

        apagardisci.setText("Apagar Disciplina");
        apagardisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagardisciActionPerformed(evt);
            }
        });

        jButton3.setText("Listar Cursos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Listar Disciplinas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        apagaraluno.setText("Apagar Aluno");
        apagaraluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagaralunoActionPerformed(evt);
            }
        });

        jButton7.setText("Listar Alunos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel13.setText("Curso");

        jLabel14.setText("Aluno");

        jLabel15.setText("Disciplina");

        jLabel16.setText("Dentro do Curso");

        jLabel17.setText("Listar");

        jLabel18.setText("Individual");

        disciapagar.setText("Apagar Disciplina");
        disciapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciapagarActionPerformed(evt);
            }
        });

        jButton6.setText("Apagar Aluno");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        apagacurse.setText("Apagar Curso");
        apagacurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagacurseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idcursolistar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idcursolistar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idcursolistar2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(disciapagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(apagacurse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apagaraluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apagardisci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(apagarcurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(disciapagar)
                                    .addComponent(apagardisci)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton7)
                                    .addComponent(apagarcurso)
                                    .addComponent(apagacurse)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apagaraluno)
                                    .addComponent(jButton2))
                                .addGap(29, 29, 29)))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idcursolistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idcursolistar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idcursolistar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Listar", jPanel5);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //resgeral.setText(osCursoDisci.get(Integer.parseInt(idcursolistar.getText()) - 1).getNome());
        //resgeral.setText(String.valueOf(osCursoDisci));
        for (int x = 0; x < osCursoDisci.size(); x++) {
            if (idcursolistar.getText().equals(osCursoDisci.get(x).getNome())) {
                resgeral.setText("ID do Curso" + " " + osCursoDisci.get(x).getIdCurso());
                resgeral.append(" " + idcursolistar.getText() + "\n");
                resgeral.append("-------------------------------------" + "\n");
                break;
            }
        }

        for (int x = 0; x < osCursoDisci.size(); x++) {
            if (idcursolistar.getText().equals(osCursoDisci.get(x).getNome())) {
                resgeral.append("ID da Disciplina " + osCursoDisci.get(x).getIdDisciplina() + " " + osCursoDisci.get(x).getNomed() + "\n");

            } else {

            }

        }
        if (idcursolistar.getText().isEmpty()) {
            resgeral.setText(" ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void inscreverBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscreverBTActionPerformed

        // TODO add your handling code here:
        Formando formando = new Formando();
        formando.setNomef(nome.getText());
        formando.setMasculino(String.valueOf(sexo.getSelectedItem()));
        if (tele.getText().isEmpty()) {
        } else {
            formando.setTelefones(Integer.parseInt(tele.getText()));
        }
        if (nome.getText().isEmpty() || tele.getText().isEmpty()) {
            res.setText("");
            res.append("Insira todos os dados.");
        } else {
            formando.setIdFormando(idFormando++);

            try {
                osFormandos.add(formando);
                FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\Formando.txt");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(osFormandos);
                oos.close();
                fos.close();

                res.setText("");
                int y = 1;
                for (int x = 0; x < osFormandos.size(); x++) {

                    res.append(String.valueOf(y++ + " " + "ID " + osFormandos.get(x).getIdFormando()) + " | " + "Nome " + osFormandos.get(x).getNomef() + " | " + "Sexo " + osFormandos.get(x).getMasculino() + " | " + "Telefone " + osFormandos.get(x).getTelefones() + "\n");
                }

            } catch (IOException ioe) {
                ioe.printStackTrace();
            }

        }

        // =======================================================================================================
        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\IDES.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(idFormando);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }


    }//GEN-LAST:event_inscreverBTActionPerformed

    private void addDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDisciplinasActionPerformed
        CursoDisci cursins = new CursoDisci();

        cursins.setIdCurso(Integer.parseInt(idCursodis.getText()));
        cursins.setNome(osCursos.get(Integer.parseInt(idCursodis.getText()) - 1).getNome());

        cursins.setIdDisciplina(Integer.parseInt(idDisciplinadis.getText()));
        cursins.setNomed(asDisciplinas.get(Integer.parseInt(idDisciplinadis.getText()) - 1).getNome());

        osCursoDisci.add(cursins);

        Resdis1.setText("Disciplina adicionada");
        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\cursoedisci.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(osCursoDisci);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }


    }//GEN-LAST:event_addDisciplinasActionPerformed

    private void createDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDisciplinasActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Disciplinas disciplina = new Disciplinas();

        disciplina.setNome(discitext.getText());

        // TODO add your handling code here:
        if (discitext.getText().isEmpty()) {
            Resdis.setText("");
            Resdis.append("Insira todos os dados.");
        } else {
            disciplina.setIdDisciplina(idDisciplina++);
            try {
                asDisciplinas.add(disciplina);
                FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\Disciplina.txt");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(asDisciplinas);
                oos.close();
                fos.close();
                Resdis.setText("");
                for (int x = 0; x < asDisciplinas.size(); x++) {
                    Resdis.append(String.valueOf("ID " + asDisciplinas.get(x).getIdDisciplina()) + "|" + " Nome do curso " + asDisciplinas.get(x).getNome() + "\n");
                }
            } catch (IOException ioe) {
                ioe.printStackTrace();
            }

        }
        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\IDESDISCI.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(idDisciplina);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }//GEN-LAST:event_createDisciplinasActionPerformed

    private void criarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarcursoActionPerformed
        // TODO add your handling code here:
        Cursos curso = new Cursos();

        curso.setNome(cursos.getText());
        curso.setHoras(Integer.parseInt(horascurso.getText()));
        // TODO add your handling code here:

        if (horascurso.getText().isEmpty() || cursos.getText().isEmpty()) {
            rescur.setText("");
            rescur.append("Insira todos os dados.");
        } else {
            curso.setIdCurso(idCurso++);
            try {
                osCursos.add(curso);
                FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\Curso.txt");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(osCursos);
                oos.close();
                fos.close();
                rescur.setText("");
                for (int x = 0; x < osCursos.size(); x++) {
                    rescur.append(String.valueOf("ID " + osCursos.get(x).getIdCurso()) + "|" + " Nome do curso " + osCursos.get(x).getNome() + "|" + " Horas do Curso " + osCursos.get(x).getHoras() + "\n");
                }

            } catch (IOException ioe) {
                ioe.printStackTrace();
            }

        }
        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\IDESCURSO.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(idCurso);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }

        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\IDESCurso.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(idCurso);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }


    }//GEN-LAST:event_criarcursoActionPerformed

    private void cursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursosActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:

        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setEnabledAt(2, true);
        jTabbedPane1.setEnabledAt(3, true);
        jTabbedPane1.setEnabledAt(4, true);
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);

        //Carregar Formandos
        FileInputStream fileInputStream = null;
        try {

            fileInputStream = new FileInputStream("D:\\JavaEscola\\Formando.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            osFormandos = (ArrayList<Formando>) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //Carregar Formandos+cursos

        try {

            fileInputStream = new FileInputStream("D:\\JavaEscola\\Formandocurso.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            osCursoForm = (ArrayList<CursoForm>) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //Carregar ids dos Formandos
        try {

            fileInputStream = new FileInputStream("D:\\JavaEscola\\IDES.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            idFormando = (int) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //Carregar Cursos
        try {

            fileInputStream = new FileInputStream("D:\\JavaEscola\\Curso.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            osCursos = (ArrayList<Cursos>) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        //Carregar os ids dos cursos  
        try {

            fileInputStream = new FileInputStream("D:\\JavaEscola\\IDESCURSO.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            idCurso = (int) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //Carregar os ids dos cursos  
        try {

            fileInputStream = new FileInputStream("D:\\JavaEscola\\cursoedisci.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            osCursoDisci = (ArrayList<CursoDisci>) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //Carregar as Disciplinas
        try {

            fileInputStream = new FileInputStream("D:\\JavaEscola\\Disciplina.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            asDisciplinas = (ArrayList<Disciplinas>) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //Carregar os ids das disciplinas
        try {

            fileInputStream = new FileInputStream("D:\\JavaEscola\\IDESDISCI.txt");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream);
            idDisciplina = (int) objectInputStream.readObject();
            objectInputStream.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileInputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(app.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_IniciarActionPerformed

    private void apagarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarcursoActionPerformed
        // TODO add your handling code here:
        for (int x = 0; x < osCursoDisci.size(); x++) {
            if (idcursolistar.getText().equals(osCursoDisci.get(x).getNome())) {
                osCursoDisci.remove(x);
                resgeral.setText("Curso Apagado");

            }
        }

        for (int x = 0; x < osCursoForm.size(); x++) {
            if (idcursolistar.getText().equals(osCursoForm.get(x).getNome())) {
                osCursoForm.remove(x);
            }
        }


    }//GEN-LAST:event_apagarcursoActionPerformed

    private void apagardisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagardisciActionPerformed
        // TODO add your handling code here:
        for (int x = 0; x < osCursoDisci.size(); x++) {
            if (idcursolistar.getText().equals(osCursoDisci.get(x).getNome())) {
                if (idcursolistar2.getText().equals(osCursoDisci.get(x).getNomed())) {
                    osCursoDisci.remove(x);
                    resgeral.setText("Disciplina Apagada");
                    break;
                }
            }
        }
        for (int x = 0; x < osCursoDisci.size(); x++) {
            if (idcursolistar.getText().equals(osCursoDisci.get(x).getNome())) {
                resgeral.setText("ID do Curso" + " " + osCursoDisci.get(x).getIdCurso());
                resgeral.append(" " + idcursolistar.getText() + "\n");
                resgeral.append("-------------------------------------" + "\n");
                break;
            }
        }

        for (int x = 0; x < osCursoDisci.size(); x++) {
            if (idcursolistar.getText().equals(osCursoDisci.get(x).getNome())) {
                resgeral.append("ID da Disciplina " + osCursoDisci.get(x).getIdDisciplina() + " " + osCursoDisci.get(x).getNomed() + "\n");

            } else {

            }

        }

        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\cursoedisci.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(osCursoDisci);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }//GEN-LAST:event_apagardisciActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        resgeral.setText("");
        for (int x = 0; x < osCursos.size(); x++) {
            resgeral.append(String.valueOf("ID " + osCursos.get(x).getIdCurso()) + "|" + " Nome do curso " + osCursos.get(x).getNome() + "|" + " Horas do Curso " + osCursos.get(x).getHoras() + "\n");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        resgeral.setText("");
        for (int x = 0; x < asDisciplinas.size(); x++) {
            resgeral.append(String.valueOf("ID " + asDisciplinas.get(x).getIdDisciplina()) + "|" + " Nome do curso " + asDisciplinas.get(x).getNome() + "\n");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AddFormtoCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFormtoCurActionPerformed
        // TODO add your handling code here:

        CursoForm cursao = new CursoForm();

        cursao.setIdCurso(Integer.parseInt(idcursoform.getText()));
        cursao.setNome(osCursos.get(Integer.parseInt(idcursoform.getText()) - 1).getNome());

        cursao.setIdFormando(Integer.parseInt(idformandoform.getText()));
        cursao.setNomef(osFormandos.get(Integer.parseInt(idformandoform.getText()) - 1).getNomef());

        osCursoForm.add(cursao);

        resformcur.setText("Aluno Adicionado");
        try {
            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\Formandocurso.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(osCursoForm);
            oos.close();
            fos.close();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }//GEN-LAST:event_AddFormtoCurActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //TODO add your handling code here:
        //resgeral.setText(osCursoDisci.get(Integer.parseInt(idcursolistar.getText()) - 1).getNome());
        //resgeral.setText(String.valueOf(osCursoDisci));
        for (int x = 0; x < osCursoForm.size(); x++) {
            if (idcursolistar.getText().equals(osCursoForm.get(x).getNome())) {
                resgeral.setText("ID do Curso" + " " + osCursoForm.get(x).getIdCurso());
                resgeral.append(" " + idcursolistar.getText() + "\n");
                resgeral.append("-------------------------------------" + "\n");
                break;
            }
        }

        for (int x = 0; x < osCursoForm.size(); x++) {
            if (idcursolistar.getText().equals(osCursoForm.get(x).getNome())) {

                resgeral.append("ID do Aluno " + osCursoForm.get(x).getIdFormando() + " " + osCursoForm.get(x).getNomef() + "\n");
            } else {

            }

        }
        if (idcursolistar.getText().isEmpty()) {
            resgeral.setText(" ");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        resgeral.setText("");
        for (int x = 0; x < osFormandos.size(); x++) {
            resgeral.append(String.valueOf("ID " + osFormandos.get(x).getIdFormando()) + " | " + "Nome " + osFormandos.get(x).getNomef() + " | " + "Sexo " + osFormandos.get(x).getMasculino() + " | " + "Telefone " + osFormandos.get(x).getTelefones() + "\n");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void apagaralunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagaralunoActionPerformed
        // TODO add your handling code here:
        for (int x = 0; x < osCursoForm.size(); x++) {
            if (idcursolistar.getText().equals(osCursoForm.get(x).getNome())) {
                if (idcursolistar1.getText().equals(osCursoForm.get(x).getNomef())) {
                    osCursoForm.remove(x);

                    resgeral.setText("Aluno apagado");
                    break;
                }
            }
        }
        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\Formandocurso.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(osCursoForm);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }//GEN-LAST:event_apagaralunoActionPerformed

    private void disciapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciapagarActionPerformed
        // TODO add your handling code here:

        for (int x = 0; x < asDisciplinas.size(); x++) {

            if (idcursolistar2.getText().equals(asDisciplinas.get(x).getNome())) {
                asDisciplinas.remove(x);
                resgeral.setText("Disciplina Apagada");
                break;
            }

        }
        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\Disciplina.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(asDisciplinas);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }


    }//GEN-LAST:event_disciapagarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        for (int y = 0; y < osFormandos.size() + 1; y++) {

            if (idcursolistar1.getText().equals(osFormandos.get(y).getNomef())) {
                osFormandos.remove(y);
                resgeral.setText("Aluno apagado");
                break;
            }

        }
        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\Formando.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(osFormandos);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void apagacurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagacurseActionPerformed
        // TODO add your handling code here:

        for (int x = 0; x < osCursos.size(); x++) {
            if (idcursolistar.getText().equals(osCursos.get(x).getNome())) {
                osCursos.remove(x);
                resgeral.setText("Curso Apagado");
                break;
            }
        }
        for (int x = 0; x < osCursoForm.size(); x++) {
            if (idcursolistar.getText().equals(osCursoForm.get(x).getNome())) {
                if (idcursolistar1.getText().equals(osCursoForm.get(x).getNomef())) {
                    osCursoForm.remove(x);
                    break;
                }
            }
        }
        for (int x = 0; x < osCursoDisci.size(); x++) {
            if (idcursolistar.getText().equals(osCursoDisci.get(x).getNome())) {
                osCursoDisci.remove(x);
                break;
            }
        }

        try {

            FileOutputStream fos = new FileOutputStream("D:\\JavaEscola\\Curso.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(osCursos);
            oos.close();
            fos.close();

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }//GEN-LAST:event_apagacurseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFormtoCur;
    private javax.swing.JButton Iniciar;
    private javax.swing.JTextArea Resdis;
    private javax.swing.JTextArea Resdis1;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton addDisciplinas;
    private javax.swing.JButton apagacurse;
    private javax.swing.JButton apagaraluno;
    private javax.swing.JButton apagarcurso;
    private javax.swing.JButton apagardisci;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JButton createDisciplinas;
    private javax.swing.JButton criarcurso;
    private javax.swing.JTextField cursos;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JButton disciapagar;
    private javax.swing.JTextField discitext;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextField horascurso;
    private javax.swing.JTextField idCursodis;
    private javax.swing.JTextField idDisciplinadis;
    private javax.swing.JTextField idcursoform;
    private javax.swing.JTextField idcursolistar;
    private javax.swing.JTextField idcursolistar1;
    private javax.swing.JTextField idcursolistar2;
    private javax.swing.JTextField idformandoform;
    private javax.swing.JButton inscreverBT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField nome;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JTextArea res;
    private javax.swing.JTextArea rescur;
    private javax.swing.JTextArea resformcur;
    private javax.swing.JTextArea resgeral;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField tele;
    // End of variables declaration//GEN-END:variables

}
